### ISSUE TITLE
Create Service

### ISSUE THREAD

**Issue by oliverhausler** [attach-live/attach-social-starter#1]
![image](https://cloud.githubusercontent.com/assets/8090341/24825881/8897fd14-1bdd-11e7-8ef5-5d5752029ea3.png)

- [x] Please show the leading slash in the dropdown, like `/provider/type/identifier`.
- [ ] Allow entering the url directly (if not used within showroom), add to the dropdown if valid.
- [ ] Show an error if getItem() fails (unallowed content): "Oops, we're still in beta."
- [ ] We'll move the video unit to the upper left. Not because the design is better, but so we can show more flexibility.
- [ ] Use non-round avatars here.

**Comment by dodekeract** [comment]
Whoops, didn't see that this has some details that I missed.
